### ISSUE TITLE
Java compatibility

### ISSUE THREAD

**Issue by rajam1215** [ismaeldivita/chip-navigation-bar#1]
Hello @ismaeldivita 

Please make this library for java compatible, so we can use in java project also. It is very good looking working is there.

Thanks

**Comment by ismaeldivita** [comment]
In a java project, you may need to add this to your dependency since this is a Kotlin library
`implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"`

**Comment by rajam1215** [comment]
Hello @ismaeldivita 

i know this thing, but i need java compatible code implementation, like onClick listener of menu, onItem click listener, now it is base on kotline language, i want java compatible code for this library.

Thanks

**Comment by rajam1215** [comment]
> In a java project, you may need to add this to your dependency since this is a Kotlin library
> `implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"`

Hello @ismaeldivita

i know this thing, but i need java compatible code implementation, like onClick listener of menu, onItem click listener, now it is base on kotlin language, i want java compatible code for this library.

Thanks

**Comment by rajam1215** [comment]
> In a java project, you may need to add this to your dependency since this is a Kotlin library
> `implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"`

Hello @ismaeldivita 
i know this thing, but i need java compatible code implementation, like onClick listener of menu, onItem click listener, now it is base on kotlin language, i want java compatible code for this library.

Thanks

**Comment by ismaeldivita** [comment]
This is not working for you? 🤔 
```java
menu.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {
    @Override
    public void onItemSelected(int id) {
        // TODO
    }
});
```

**Comment by rajam1215** [comment]
> This is not working for you? 
> 
> ```java
> menu.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {
>     @Override
>     public void onItemSelected(int id) {
>         // TODO
>     }
> });
> ```

Hello @ismaeldivita 

Why it's not working for me, While the time i close that issue, if i want any solution regarding library, i will come back to you.

Thanks
