### ISSUE TITLE
Remove round light background of selected icon

### ISSUE THREAD

**Issue by Dheerajtiwarri** [ismaeldivita/chip-navigation-bar#102]
<img width="76" alt="Screenshot 2023-03-01 at 6 00 15 PM" src="https://user-images.githubusercontent.com/43986605/222139932-d3fde661-fe0d-4664-936f-22ab10b31399.png">
Kindly help me to figure out, how can we remove the light color round background of the selected menu item.

**Comment by ismaeldivita** [comment]
You can try tweak the `cnb_backgroundColor` for each item

https://github.com/ismaeldivita/chip-navigation-bar#xml-custom-attributes

**Comment by Dheerajtiwarri** [comment]
Worked, Thank you :)
