### ISSUE TITLE
Failed to use it in viewpager (java )

### ISSUE THREAD

**Issue by rahat14** [ismaeldivita/chip-navigation-bar#12]

**Comment by ismaeldivita** [comment]
No intentions to support viewpager

https://material.io/components/bottom-navigation/#behavior
> An in-place cross-fade animation is recommended for transitions between bottom navigation destinations. Lateral (side-to-side) transitions may imply a peer relationship between the items that does not exist, or mislead users into thinking they can use gestures to navigate between sections.
