### ISSUE TITLE
SetOnItemSelectedListener() being called twice on clicking once.

### ISSUE THREAD

**Issue by Arpit0492** [ismaeldivita/chip-navigation-bar#14]
So when I am clicking on one item once, the fragment matching with the clicked item id is being called twice. I don't think this is happening because of my code.

**bottomBar is the chip-navigation-bar**

`binding.bottomBar.setOnItemSelectedListener { id ->
            when (id) {
                R.id.home1 -> {
                    setFragment(HomeFragment1())
                }
                R.id.home2 -> {
                    setFragment(HomeFragment2())
                }
                R.id.home3 -> {
                    setFragment(HomeFragment3())
                }
            }
        }`

**Comment by simongiesen** [comment]
yep, it's called twice here as well - plz fix

**Comment by ismaeldivita** [comment]
I just release a new version fixing this issue. Let me know if it works for you guys.
