### ISSUE TITLE
setOnItemSelectedListener in Java?

### ISSUE THREAD

**Issue by simongiesen** [ismaeldivita/chip-navigation-bar#15]
great library so far. How can I implement the delegate method in Java?

... setOnItemSelectedListener( ...

**Comment by simongiesen** [comment]
it's done like this

navBar.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {


            @Override
            public void onItemSelected(int i) {

                Log.i("info", "item tapped " + i);

            }
        });

**Comment by simongiesen** [comment]
PS: The event is fired twice, please fix

**Comment by ismaeldivita** [comment]
I just release a new version fixing this issue. Let me know if it works for you.

**Comment by simongiesen** [comment]
> I just release a new version fixing this issue. Let me know if it works for you.

Thank you very much for your efforts, I will test it!
