### ISSUE TITLE
OnItemSelctedListener Java

### ISSUE THREAD

**Issue by tsplay** [ismaeldivita/chip-navigation-bar#16]
I am not sure what I have to write in the OnItemSelctedListener in Java can you send me an Example sir?

This is a Part of my Current Code what do it Need to Change? i want to open an New Actvity on Click Item

public class MainActivity extends AppCompatActivity {

 

    ChipNavigationBar chipNavigationBar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main_test);

        chipNavigationBar = findViewById(R.id.menu);

        chipNavigationBar.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {

            @Override
            public void onItemSelected(int id) {
               Toast.makeText(MainActivity.this, "Test", Toast.LENGTH_SHORT).show();
            }
        });

    }

**Comment by yashas003** [comment]
//Hope this might help you

ChipNavigationBar chipNavigationBar;


@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main_test);

    chipNavigationBar = findViewById(R.id.menu);

    chipNavigationBar.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {

        @Override
        public void onItemSelected(int id) {
           switch(id) {
				case R.id.item1:
					Toast.makeText(MainActivity.this, "First item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item2:
					Toast.makeText(MainActivity.this, "Second item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item3:
					Toast.makeText(MainActivity.this, "Third item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item4:
					Toast.makeText(MainActivity.this, "fourth item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				.
				.
				.
			}
        }
    });
}

**Comment by yashas003** [comment]
//Hope this might help you

<ChipNavigationBar chipNavigationBar;


@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main_test);

    chipNavigationBar = findViewById(R.id.menu);

    chipNavigationBar.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {

        @Override
        public void onItemSelected(int id) {
           switch(id) {
				case R.id.item1:
					Toast.makeText(MainActivity.this, "First item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item2:
					Toast.makeText(MainActivity.this, "Second item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item3:
					Toast.makeText(MainActivity.this, "Third item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item4:
					Toast.makeText(MainActivity.this, "fourth item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				.
				.
				.
			}
        }
    });
}>

**Comment by yashas003** [comment]
Hope this helps you :)

`ChipNavigationBar chipNavigationBar;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main_test);

    chipNavigationBar = findViewById(R.id.menu);

    chipNavigationBar.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {

        @Override
        public void onItemSelected(int id) {
           switch(id) {
				case R.id.item1:
					Toast.makeText(MainActivity.this, "First item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item2:
					Toast.makeText(MainActivity.this, "Second item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item3:
					Toast.makeText(MainActivity.this, "Third item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item4:
					Toast.makeText(MainActivity.this, "fourth item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				.
				.
				.
			}
        }
    });
}
`

**Comment by yashas003** [comment]
Hope this helps you :)

```
ChipNavigationBar chipNavigationBar;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main_test);

    chipNavigationBar = findViewById(R.id.menu);

    chipNavigationBar.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {

        @Override
        public void onItemSelected(int id) {
           switch(id) {
				case R.id.item1:
					Toast.makeText(MainActivity.this, "First item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item2:
					Toast.makeText(MainActivity.this, "Second item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item3:
					Toast.makeText(MainActivity.this, "Third item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				case R.id.item4:
					Toast.makeText(MainActivity.this, "fourth item clicked :)", Toast.LENGTH_SHORT).show();
				break;
				.
				.
				.
			}
        }
    });
}

```

**Comment by tsplay** [comment]
Thank you very much sir. Gesendet von Mail für Windows 10 Von: Yashas GowdaGesendet: Montag, 30. Dezember 2019 07:45An: ismaeldivita/chip-navigation-barCc: tsplay; AuthorBetreff: Re: [ismaeldivita/chip-navigation-bar] OnItemSelctedListener Java (#16) Hope this helps you :)ChipNavigationBar chipNavigationBar; @Overrideprotected void onCreate(Bundle savedInstanceState) {    super.onCreate(savedInstanceState);    setContentView(R.layout.activity_main_test);     chipNavigationBar = findViewById(R.id.menu);     chipNavigationBar.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {         @Override        public void onItemSelected(int id) {           switch(id) {                               case R.id.item1:                                       Toast.makeText(MainActivity.this, "First item clicked :)", Toast.LENGTH_SHORT).show();                               break;                               case R.id.item2:                                       Toast.makeText(MainActivity.this, "Second item clicked :)", Toast.LENGTH_SHORT).show();                               break;                               case R.id.item3:                                       Toast.makeText(MainActivity.this, "Third item clicked :)", Toast.LENGTH_SHORT).show();                               break;                               case R.id.item4:                                       Toast.makeText(MainActivity.this, "fourth item clicked :)", Toast.LENGTH_SHORT).show();                               break;                               .                               .                               .                       }        }    });} —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
