### ISSUE TITLE
problem with layout when clicked a item menu

### ISSUE THREAD

**Issue by delvin081299** [ismaeldivita/chip-navigation-bar#17]
my mainactivity.java code is
package com.asus.eins;

import androidx.annotation.MenuRes;
import androidx.appcompat.app.AppCompatActivity;
import androidx.viewpager.widget.ViewPager;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.MenuItem;
import android.widget.Toast;

import com.asus.eins.Fragment.Home;
import com.ismaeldivita.chipnavigation.ChipNavigationBar;

import java.util.ArrayList;
import java.util.List;

public class Dashboard extends AppCompatActivity {

    ChipNavigationBar chipNavigationBar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_dashboard);

        chipNavigationBar = findViewById(R.id.menu);

        chipNavigationBar.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {

            @Override
            public void onItemSelected(int id) {
                switch (id) {
                    case R.id.home:
                        chipNavigationBar.setMenuResource(R.layout.fragment_home);
                        break;
                }
            }
        });
    }
}

and my mainactivity.xml is
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:tools="http://schemas.android.com/tools"
    android:background="#2CA7E0"
    tools:context=".Dashboard">

    <com.ismaeldivita.chipnavigation.ChipNavigationBar
        android:id="@+id/menu"
        android:layout_width="match_parent"
        android:layout_height="70dp"
        android:layout_alignParentBottom="true"
        android:background="#fff"
        android:elevation="16dp"
        android:gravity="center"
        android:padding="8dp"
        app:cnb_menuResource="@menu/bottom_menu" >

    </com.ismaeldivita.chipnavigation.ChipNavigationBar>

</RelativeLayout>

i set on item selected with my fragment
but when i clicked a item menu my app is force close and show a error expecting menu, got relative layout

**Comment by ismaeldivita** [comment]
Hi 👋

```java
chipNavigationBar.setMenuResource(R.layout.fragment_home);
```

Crashing because you're updating the `menuResource` with a layout file when clicking on a menu item.
