### ISSUE TITLE
Get menu items ?

### ISSUE THREAD

**Issue by gaiththewolf** [ismaeldivita/chip-navigation-bar#18]
**can you add get menu to change menu item title dynamically ?**

**Comment by ismaeldivita** [comment]
Hi 👋 
Just setting another menu via `setMenuResource` is not enough? 
Tell me more about your use case and what you're trying to achieve.

**Comment by gaiththewolf** [comment]
Hi :wave:

In my case i need when a user choose language in splashscreen, in the main activity that contains the navbar home item will be for example home-En or Home-fr ...
I need to change it dynamically

**Comment by ismaeldivita** [comment]
Well, I don't see this as an issue of the library. 

BTW take a look at this article it may help you how to propper handle language change on runtime 
https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758
