### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ismaeldivita** [ismaeldivita/chip-navigation-bar#21]

**Comment by nekooei** [comment]
Hello,
Can you provide information about this issue?
I would like to help you :)

**Comment by ismaeldivita** [comment]
Hi 👋 

To be honest I have more question about the RTL itself than the implementation. 
I'll put them here, maybe you or someone could help.

1. Should the icon and label position be inverted for RTL?
2. The badge should be displayed in the opposite side? 
3. On the badge, should we display +99 or 99+?
4. Should we invert the menu items order when we parse the menu.xml?
5. For the vertical mode should we always consider the panel on right side for RTL?

**Comment by nekooei** [comment]
for the first question:
I applied RTL direction for my layouts and the library works fine for RTL
second, third :
yes
fourth: 
we don't need this can be handled by the layout direction
fifth: 
I have no Idea

**Comment by ismaeldivita** [comment]
> Should we invert the menu items order when we parse the menu.xml?
According to google
![Screenshot 2020-03-08 at 13 00 30](https://user-images.githubusercontent.com/7879502/76163297-d48a8000-613c-11ea-9196-86c5c6f06b56.png)
