### ISSUE TITLE
setOnItemSelectedListener(listener: OnItemSelectedListener)

### ISSUE THREAD

**Issue by anohene1** [ismaeldivita/chip-navigation-bar#22]
I want to make each menu item open a new activity but I'm having trouble implementing this method. Can someone explain to me how I should do it

**Comment by ismaeldivita** [comment]
Take a look at this issue https://github.com/ismaeldivita/chip-navigation-bar/issues/16
I hope it helps.

**Comment by anohene1** [comment]
I program with Kotlin so unfortunately that thread doesn't help. I'd really appreciate your help. Thanks

**Comment by ismaeldivita** [comment]
@anohene1 
Check the library sample app.

https://github.com/ismaeldivita/chip-navigation-bar/blob/cb74e95dc93352199ad9878e32aa366f1744ee8d/sample/src/main/java/com/ismaeldivita/chipnavigation/sample/HorizontalModeActivity.kt#L26
