### ISSUE TITLE
How to customize radius for background menu item?

### ISSUE THREAD

**Issue by abdulazizahwan** [ismaeldivita/chip-navigation-bar#23]

**Comment by ismaeldivita** [comment]
There is no way to customize the radius right now. Planning to add as an attribute on the next release.

**Comment by abdulazizahwan** [comment]
Wow thanks a lot. And i have questions how do we change icon size and text size? There is attribute for that? Thanks for you answer.

**Comment by ismaeldivita** [comment]
You can't customize the icon size and text size right now but I'm planning to provide all possible configurations properties on the next release.

- badge text size
- radius
- text size
- icon size
- internal paddings

**Comment by abdulazizahwan** [comment]
Thanks a lot, I'll be happy to waiting that updates 🔥

**Comment by abdulazizahwan** [comment]
How do we show only label, and when we click it will be show icon?

![Navbar](https://user-images.githubusercontent.com/32432134/75319519-6c67ae80-589f-11ea-97bd-3cf6d2ee1bd3.png)

**Comment by ismaeldivita** [comment]
This is not gonna be supported by the library.

**Comment by abdulazizahwan** [comment]
Ok thanks
