### ISSUE TITLE
Support for a different Font Family

### ISSUE THREAD

**Issue by everalf1995** [ismaeldivita/chip-navigation-bar#24]
Is there a way to change the font family?

**Comment by ismaeldivita** [comment]
I still need to work to improve the font customisation. But for now I know this is not exactly what you want but maybe just set the font into project may help you. Check the sample, it's using a custom font.

https://github.com/ismaeldivita/chip-navigation-bar/blob/cb74e95dc93352199ad9878e32aa366f1744ee8d/sample/src/main/res/values/styles.xml#L11

**Comment by ismaeldivita** [comment]
Fixed. 
Will be available on the next release

**Comment by ismaeldivita** [comment]
https://github.com/ismaeldivita/chip-navigation-bar/releases/tag/1.3.0
