### ISSUE TITLE
How to set an icon when the apps starts?

### ISSUE THREAD

**Issue by samkey123** [ismaeldivita/chip-navigation-bar#29]
I tried a method but the app crash. How can I solve this?

**Comment by ismaeldivita** [comment]
Just call `setItemSelected(id: Int)` with your menu item id

**Comment by samkey123** [comment]
Hey, I'm again. That's the code that I'm using to call and the error message.

BottomNavigationView navigation = findViewById(R.id.navigation_view);
navigation.setSelectedItemId(R.id.home);


java.lang.ClassCastException: com.ismaeldivita.chipnavigation.ChipNavigationBar cannot be cast to com.google.android.material.bottomnavigation.BottomNavigationView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)

**Comment by ismaeldivita** [comment]
As the error says you're trying to cast the ChipNavigationBar to the Google NavigationView 

```kotlin
ChipNavigationBar navigation = (ChipNavigationBar) findViewById(R.id.navigation_view);
```

**Comment by samkey123** [comment]
Oooo it works! Thanks!
