### ISSUE TITLE
Kotlin cannot access kotlin.jvm.functions.Function1 when calling kotlin function with java lambda

### ISSUE THREAD

**Issue by JagadishaIncture** [ismaeldivita/chip-navigation-bar#39]
chipNavigationBar.setOnItemSelectedListener(new ChipNavigationBar.OnItemSelectedListener() {
            @Override
            public void onItemSelected(int i) {

                if (i==R.id.menu_home) {

                    LoadFrag(new HomeFrag());

                } else if (i == R.id.menu_fav) {

                    LoadFrag(new FavFrag());

                }

            }
        });

while useing above event iam geting error as below during compiling

error: cannot access Function1
class file for kotlin.jvm.functions.Function1 not found

**Comment by ismaeldivita** [comment]
Check the note on [README](https://github.com/ismaeldivita/chip-navigation-bar#gradle) you probably gonna need to add the kotlin std lib

**Comment by Cryston98** [comment]
Add this  dependencies 
    implementation 'com.ismaeldivita.chipnavigation:chip-navigation-bar:1.3.4'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.3.70' // for use bottom nav
