### ISSUE TITLE
Add Real fragments

### ISSUE THREAD

**Issue by rajam1215** [ismaeldivita/chip-navigation-bar#4]
How to Add fragments instead of colors
when click on chip i want to add fragment in container like that

or add fragments in arraylist and pass to chip navigation bar
ArrayList fragList = new ArrayList<>();
fragList.add(new firstFragement());
4 more.

please look in to it

**Comment by ismaeldivita** [comment]
The colored container is just a sample.
Just add your[ Fragment.Transaction](https://developer.android.com/guide/components/fragments) on `OnItemSelectedListener` based on the selected menu item.

**Comment by mohit1050** [comment]
ho to do that
