### ISSUE TITLE
Change icon of menu item programmatically 

### ISSUE THREAD

**Issue by spink98** [ismaeldivita/chip-navigation-bar#48]
Is there any way to change the icon of a menu item from code? For example set a drawable as an image when a user logs in?

**Comment by ismaeldivita** [comment]
At the moment you can't dynamically change the icons.

What you can do is update the bottom bar with a new `menu.xml` with the authenticated icon.
You can use [setMenuResource](https://github.com/ismaeldivita/chip-navigation-bar/blob/26a438f45bb322213a254c29e49d782f85acb0ea/chip-navigation-bar/src/main/java/com/ismaeldivita/chipnavigation/ChipNavigationBar.kt#L78) for that

**Comment by spink98** [comment]
Ah OK. Unfortunately, the image must be set at the moment via a web download. So I cannot use a menu already created from resources since this cannot be dynamically created from code. It will mean that I will use a generic icon for the user section! Thanks anyway! The library is still excellent!
