### ISSUE TITLE
issue regarding the ".setOnItemSelectedListener"

### ISSUE THREAD

**Issue by tauqirpasha** [ismaeldivita/chip-navigation-bar#49]
"java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ismaeldivita.chipnavigation.ChipNavigationBar.setOnItemSelectedListener(com.ismaeldivita.chipnavigation.ChipNavigationBar$OnItemSelectedListener)' on a null object reference"

**Comment by ismaeldivita** [comment]
Post your code, it seems your menu is simply null, not a library issue.

**Comment by tauqirpasha** [comment]
fixed the issues last night. thank you !
