### ISSUE TITLE
change the menutext and icon

### ISSUE THREAD

**Issue by godsey-sics** [ismaeldivita/chip-navigation-bar#50]
Is there any way to change the text and icon of a menu item programmatically? For eg:if the user has a store. need to show the  store image and store name on fourth item

**Comment by ismaeldivita** [comment]
I think its the same was raised here https://github.com/ismaeldivita/chip-navigation-bar/issues/48

At the moment there is no way to do that, I'm planning to add that soon

**Comment by godsey-sics** [comment]
Hi,
    Can you add this feature, it's very urgent for me.  I have a task to do
that. So don't feel bad when I'm asking this question
Kind regards
Godsey anna kunjumon

**Comment by godsey-sics** [comment]
can you give any idea to do that
