### ISSUE TITLE
problem with changing the color of the text

### ISSUE THREAD

**Issue by mysterious588** [ismaeldivita/chip-navigation-bar#53]
there is no way to change the color of the text
Tried **textAppearance** but it doesn't work with **textColor**, it always follows the theme's primary color

**Comment by ismaeldivita** [comment]
Hi 👋 

Just published a new release `1.3.4 `. Let me know if this fixes your problem.

**Comment by mysterious588** [comment]
Hello,

No, textAppearance still doesn't change the color of the text.
However, I managed to change the color of the text through the **menu** resource file of the view.
Changing the color of the icon also changes the color of the text which is good enough for my problem

``` app:cnb_iconColor="@color/colorText" ```

**Comment by ismaeldivita** [comment]
Yes, I can see the problem now, `textAppeareance` color is being overwrite by the `app:cnb_iconColor` | `app:cnb_textColor`.

By default text will follow the icon color if not specified by `app:cnb_textColor`

**Comment by mysterious588** [comment]
```app:cnb_textColor``` is actually what I needed, for some reason, android studio couldn't find it so I had to work around and implement textAppearance

Many thanks, I'm closing the issue now
