### ISSUE TITLE
Unresolved class error

### ISSUE THREAD

**Issue by Mustangodhra** [ismaeldivita/chip-navigation-bar#56]
when i use the dependencies, the "**tools:context**" field of every layout file shows error.
i am using it with java so used this dependencies:

    implementation 'com.ismaeldivita.chipnavigation:chip-navigation-bar:1.3.2'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.3.72'

the error shows " **Unresolved class 'class_name'** ".
please help me with this.

**Comment by SunnerLi** [comment]
Hi,
Although I don't encounter this problem, I also use java with this package.
The editor I use is android studio.
Just share some experience and show in the following:
1. Set the buildScript which assign gradle the correct kotlin version:
```gradle
buildscript {
    ext.kotlin_version = '1.3.30'
    ext.gradle_version = '3.1.0'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$gradle_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```
2. Add kotlin plugin:
```gradle
apply plugin: 'kotlin-android'
```
3. Add dependencies:
```gradle
dependencies {
    implementation 'com.ismaeldivita.chipnavigation:chip-navigation-bar:1.3.4'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
```
4. Click `Sync now` text and rebuild the project.

**Comment by ismaeldivita** [comment]
Closing due inactivity
