### ISSUE TITLE
Unable to Install in my Java Project

### ISSUE THREAD

**Issue by katesaikishore** [ismaeldivita/chip-navigation-bar#58]
```
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.3.72'
```

I have imported project successfully
And yet cant use  `app:cnb_menuResource` in my XML file.

Android max API 30
min API level 23

Sync with Gradle and cleared caches and restarted no use.

**Comment by katesaikishore** [comment]
My mistake didn't design the menu

**Comment by elmundomusical4** [comment]
How did you solve it?? I have the same problem! 😓

**Comment by karelkryda** [comment]
Did you found how to solve it?
