### ISSUE TITLE
How to change Icon when selected? 

### ISSUE THREAD

**Issue by syafiqadibafham** [ismaeldivita/chip-navigation-bar#63]
I already do selector.xml for each icon and i program each icon for true and false android:state_checked. but it didn't work. did anyone have the solution?

**Comment by ismaeldivita** [comment]
That's probably an issue on the library side. I'll take a look

**Comment by Mr-Akki-Jangir** [comment]
Please Resolve this issue asap.

**Comment by ismaeldivita** [comment]
It's working with `state_selected`
