### ISSUE TITLE
Cannot resolve class com.ismaeldivita.chipnavigation.ChipNavigationBar 

### ISSUE THREAD

**Issue by neelgpatel20** [ismaeldivita/chip-navigation-bar#66]
Class referenced in the layout file, com.ismaeldivita.chipnavigation.ChipNavigationBar, was not found in the project or the libraries

**Comment by neelgpatel20** [comment]
minSdkVersion 23

dependencies {
    implementation 'com.ismaeldivita.chipnavigation:chip-navigation-bar:1.3.3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}

**Comment by ismaeldivita** [comment]
Library moved to jitpack

```gradle
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
```

```gradle 
implementation 'com.ismaeldivita.chipnavigation:chip-navigation-bar:1.3.4'
```

**Comment by yashyon** [comment]
not working...
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.ismaeldivita.chipnavigation:chip-navigation-bar:1.3.4.
     Required by:
         project :app

This error is coming ...

**Comment by ashu9152** [comment]
still same error

**Comment by fakhrulrz24** [comment]
@ismaeldivita same error still happens, could you give another solution?

**Comment by ashu9152** [comment]
when i am using jcenter() without using  maven { url 'https://jitpack.io' } it works. But when I remove jcenter() and add  maven { url 'https://jitpack.io' } same error happens.

**Comment by ismaeldivita** [comment]
Please post your root and module `build.gradle`

**Comment by ismaeldivita** [comment]
https://github.com/ismaeldivita/chip-navigation-bar/pull/74

**Comment by JaegerCodes** [comment]
Solved by adding:
maven { url 'https://jitpack.io' }

in:
settings.gradle (Project Settings)

**Comment by lttp2509** [comment]
Nice one, man

**Comment by shakib522** [comment]
Still get error.Can not resolve the chip Navigation.can anyone help me?
I am using Android studio bumble bee

**Comment by kanha-jii** [comment]
> when i am using jcenter() without using maven { url 'https://jitpack.io' } it works. But when I remove jcenter() and add maven { url 'https://jitpack.io' } same error happens.

thanks adding jcenter works for me

**Comment by ErfanAzadi** [comment]
Adding jcenter() just worked for me too, Thanks!
