### ISSUE TITLE
setItemSelected calls setOnItemSelectedListener everytime

### ISSUE THREAD

**Issue by AkshayAshokCode** [ismaeldivita/chip-navigation-bar#69]
**Context**: when the user clicks on any item from _chip-navigation-bar_ then _setOnItemSelectedListener_ is called then he has to pass through a Dialog box in which if he presses "No" he will stay in the current activity. 
**Problem**: So the problem is after pressing "No" the clicked item stays selected so if I try to set the previous/default item selected by _setItemSelected_ then it also calls _setOnItemSelectedListener_ again which repeats the Dialog box part!! Is there any recommended way to fix it?

Thank you!

**Comment by ismaeldivita** [comment]
This https://github.com/ismaeldivita/chip-navigation-bar/pull/76 will open the `setItemSelected` function and enable you to send false to `dispatchAction`, this will prevent the listeners to be triggered.

**Comment by AkshayAshokCode** [comment]
'setItemSelected(int, boolean, boolean)' has private access in 'com.ismaeldivita.chipnavigation.ChipNavigationBar'
This function doesn't have a public access yet. 
I add this dependency "'com.github.ismaeldivita:chip-navigation-bar:1.3.4'" is there any update to it in which I can find setItemSelected as Public?
Thank you for the Reply!

**Comment by ismaeldivita** [comment]
This change was not released yet

**Comment by AkshayAshokCode** [comment]
When can we expect it to be released?⏳︎
