### ISSUE TITLE
Failed to resolve: com.ismaeldivita.chipnavigation:chip-navigation-bar:1.3.4

### ISSUE THREAD

**Issue by ashu9152** [ismaeldivita/chip-navigation-bar#72]
maven { url 'https://jitpack.io' }

 minSdkVersion 25

implementation 'com.ismaeldivita.chipnavigation:chip-navigation-bar:1.3.4'
implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.5.10'

**Comment by milon27** [comment]
same issue

**Comment by gargVader** [comment]
Same issue

**Comment by gargVader** [comment]
@ismaeldivita

**Comment by milon27** [comment]
solved it here: https://github.com/ismaeldivita/chip-navigation-bar/pull/73

**Comment by Dhina17** [comment]
Fixed. https://github.com/ismaeldivita/chip-navigation-bar/pull/74
