### ISSUE TITLE
Change animation duration

### ISSUE THREAD

**Issue by Nekidev** [ismaeldivita/chip-navigation-bar#78]
Is it possible to change the duration of the animation?

**Comment by ismaeldivita** [comment]
No, but I can try to add on the next version apis for that

**Comment by rahulnarang21** [comment]
Is there any update on the duration of the animation?

**Comment by Nekidev** [comment]
> Is there any update on the duration of the animation?
> 

Nope

**Comment by ismaeldivita** [comment]
Set duration is available on https://github.com/ismaeldivita/chip-navigation-bar/releases/tag/1.4.0
