### ISSUE TITLE
Added dependencies but no tags found in xml

### ISSUE THREAD

**Issue by ChanShiraz** [ismaeldivita/chip-navigation-bar#91]
Hi there,
I have added dependencies but no tags were found in xml, anyone please guide me.

**Comment by rishabhsingh2002** [comment]
Same issue !

**Comment by karelkryda** [comment]
Did you found any solution?

**Comment by alex99-dev** [comment]
Add JitPack to your gradle configuration:
```
allprojects {
    repositories {
     .......
        maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by ceduardolima** [comment]
I had the same issue and I add the jitPack, but isn't work.
Is showing this message:

Failed to resolve: com.github.ismaeldivita:chip-navigation-bar:1.3.4
Show in Project Structure dialog
Affected Modules: app

**Comment by ismaeldivita** [comment]
Probably missing the jitpack configuration, depending on how your project is configured it may be located on the root `build.gradle`  or `settings.gradle`

Here you can find the versions on jitpack are deployed as expected https://jitpack.io/#ismaeldivita/chip-navigation-bar
