### ISSUE TITLE
Failed to resolve com.github.ismaeldivita:cip-navigation-bar:1.4.0

### ISSUE THREAD

**Issue by meija1** [ismaeldivita/chip-navigation-bar#94]
Im not sure why its happening

**Comment by KanishkKhurana** [comment]
facing the same issue! please resolve this asap

**Comment by ismaeldivita** [comment]
Probably missing the jitpack configuration, depending on how your project is configured it may be located on the root `build.gradle`  or `settings.gradle`

Here you can find the versions on jitpack are deployed as expected https://jitpack.io/#ismaeldivita/chip-navigation-bar

**Comment by jayant1441** [comment]
I added jitpack in settings.gradle and added the dependency as well but still facing the issue

![image](https://user-images.githubusercontent.com/34379105/182676547-8cb14a21-895b-46e1-8bf6-d58a8e627f5a.png)

![image](https://user-images.githubusercontent.com/34379105/182676675-9734f821-0e45-4dee-8589-b50b717beb97.png)

![image](https://user-images.githubusercontent.com/34379105/182676968-c6f3406d-cf63-4120-9eb2-b0907bac32f3.png)

**Comment by bhaskar966** [comment]
I am facing the same issue. Please give ant other solution.

**Comment by ntagky** [comment]
Adding `maven { url 'https://jitpack.io' }` into also `dependencyResolutionManagement` solved the problem.
